### PR TITLE
131 need feedback on routing decision

### PR DESCRIPTION
**Pull request by Orta21**
In developing this i ran into a few problems. My initial thought for this was to create one component, no routing. The agreement would be made. which changes the state and then it would flip to the providers. The problem with this approach is when the users get redirected back to the widget after approving a certain provider they would need to accept the terms again. We could solve this with adding if the agreement is accepted in local storage but then all future widget requests will not show the agreement. (If they accept it once is that good enough?)

Second approach was agreement to be its own url and once clicked it would go to the connect widget url. Problem is users could technically bypass the agreement by changing the url.

This also bring up the conversation of whether or not we want to go with a completely different approach for the widget and not do it url based all together.

Also this is the design for the agreement. Let me know what you guys think!
Screen Shot 2022-12-22 at 3 53 50 PM

### CODE REVIEW

**Comment by leite08** [comment]
Thanks for putting this up! I like the design! Maybe test with HIPAA SOC2 logos centralized?

As, for the user accepting terms: what if we store this on the DB and retrieve upon widget load?

**Comment by Goncharo** [comment]
First, I think the design is great, good job! My comments

"We could solve this with adding if the agreement is accepted in local storage but then all future widget requests will not show the agreement. (If they accept it once is that good enough?)" ->  yes, let's do this in local storage. I think accepting once is good enough, and we can version the storage key for when we need to update our privacy policy, so it pops up again.

Design comments:
- Title: "This app uses Metriport to connect your accounts" - note the 's', maybe make the font a bit smaller?
- Section headers, let's be consistent with the caps - ie "Data" in "Health Data" shouldn't be capitalized to be consistent with the first 2 bullets, same with "Compliant"
- Section descriptions, consistency with punctuation - ie all sections should have periods, right now only the 3rd does.

Proposed working updates:
- "medical accounts" -> "health accounts"
- "Your data is secured" -> "Secure and encrypted"
- "Metriport encrypts data..." -> "Your personal data is encrypted and only accessible through your consent."
- "access to your health data..." -> "access to your health data - including sleep, workouts, and other data points."

**Comment by leite08** [comment]
Also:
- storing on local storage will require them to accept the terms again if they change browsers/devices midway through the connection process
- we don't need to store this with a timestamp on the DB, for compliance and/or disputes?

**Comment by Goncharo** [comment]
Good point about the device change - I think having them accept again on another device will be okay, as most people only have a couple devices at most, and pressing one button is a minor task.

Regarding compliance, I think it's fair to say if the user is in our db, they've accepted the ToC at that point in time, since this is a requirement in our software.

**Comment by Orta21** [comment]
Updated copy and design. I tried aligning center the icons but it looked weird since everything else is left aligned
Screen Shot 2022-12-23 at 1 39 07 PM

**Review by Goncharo — APPROVED** [review]
🚢 🚢 🚢 🚢 🚢

**Pull request merged**
