### PR TITLE
909 do not report 4xx to Sentry

### PR DESCRIPTION
**Pull request by leite08**
Ref. metriport/metriport-internal#909

### Dependencies

- Downstream: internal TBD

### Description

Adjust default handlers to not report 4xx to Sentry.

This is 1/n PRs for the ticket.

### Release Plan

- nothing special

### CODE REVIEW

**Review by Goncharo — APPROVED** [review]
LGTM - so we're on the same page, we're sure that we don't want to send any 403s to Sentry? Thinking we might be flying under the radar if auth to a provider, or CW, is borked

**Comment by leite08** [comment]
> we're sure that we don't want to send any 403s to Sentry? Thinking we might be flying under the radar if auth to a provider, or CW, is borked

That's a good catch. I'll update to only fail on `400-402` and `404+`

**Comment by leite08** [comment]
> > we're sure that we don't want to send any 403s to Sentry? Thinking we might be flying under the radar if auth to a provider, or CW, is borked
> 
> That's a good catch. I'll update to only fail on `400-402` and `404+`

OTOH, we should be (and I think we are) handling those on each respective code.

We shouldn't put (1) errors from our app being the client of an HTTP request and (2) errors from our app being the server on the same basket.

**Comment by leite08** [comment]
Adjusting some error handling code on OSS repo so we (1) don't flood the logs like we do when we have the whole error/stack on multiple lines and (2) log the minimal information about the error:

- Either lines 1 or 2 on the `catch` block is what we want.

image

image

**Comment by leite08** [comment]
Did some additional tests and added a couple of commits.

WRT `4xx` that we get when querying external services like CW and other apps like internal, those use Axios, which throws its own error. Those errors are not treated as Metriport/Zod.

By default no client related errors, including `ZodError`, will be reported to Sentry/Slack. Only routes marked with the `reportClientErrors` middleware will.

**Review by Goncharo — APPROVED** [review]
:shipit:

**Pull request merged**
