### PR TITLE
2223 ihev1 code remove

### PR DESCRIPTION
**Pull request by jonahkaye**
Ticket: #[2223](https://github.com/metriport/metriport-internal/issues/1766)

### Description

- remove ihev1 code (packages/ihe-gateway folder)

### Release Plan

- [x] Merge this
- [ ] manually remove IHE PREREQ STACK

### CODE REVIEW

**Comment by RamilGaripov** [comment]
It would save me a few minutes of scrolling thru the changes, if the description clearly stated that this ONLY removes the `packages/ihe-gateway` folder 😵‍💫 

Don't we need to also make adjustments throughout the API to stop calling v1 endpoints?

**Comment by RamilGaripov** [comment]
There's some PR checks that are failing

**Review by leite08 — APPROVED** [review]
R.I.P.

Just one missing piece: there's a reference to it on `pull-request_other.yml`, can you remove it before merging it, please?

**Review by leite08 — APPROVED** [review]
R.I.P.

Might need to manually remove the stack and/or the resources it holds. Can you add this step to the release plan, please? Happy to take the details about it to slack.

**Pull request merged**
