### PR TITLE
fix(api): api and sdk matching in docref type attribute

### PR DESCRIPTION
**Pull request by RamilGaripov**
refs. [808](https://github.com/metriport/metriport-internal/issues/808)

### Dependencies

- Upstream: _[857]_https://github.com/metriport/metriport-internal/pull/857

### Description

- Added .optional() to the documentReferenceSchema to match it to the API

### CODE REVIEW

**Review by Goncharo — CHANGES_REQUESTED** [review]
@leite08 can correct me if I'm wrong since he raised the issue, but I think we want to make the SDK match the API, not make the API match the SDK.

**Comment by leite08** [comment]
> @leite08 can correct me if I'm wrong since he raised the issue, but I think we want to make the SDK match the API, not make the API match the SDK.

Agreed, we likely added `undefined` to doc ref's `type` b/c of some response we got from CW, so we should probs make the SDK to match the API.

**Comment by leite08** [comment]
This PR has conflicts, can you solve them and let us know so we can review it again, please @RamilGaripov ?

**Comment by RamilGaripov** [comment]
This part of the issue was already resolved within the scope of this issue: https://github.com/metriport/metriport-internal/issues/799

This commit shows up as the last tracked relevant change: https://github.com/metriport/metriport/commit/e0d60b792fca1263a073f7d26f6da4d05e3ad949

**Pull request closed without merging**
