### PR TITLE
fix(api): add production url to carequality sdk

### PR DESCRIPTION
**Pull request by Orta21**
Ref. metriport/metriport-internal#1350

Ticket: #1350

### Dependencies

- Upstream: none
- Downstream: none

### Description

add production url to carequality sdk

### Testing

No testing and is only being used by internal routes triggered by us

### Release Plan

Nothing special

- [ ] Upstream dependencies are met/released
- [ ] Release NPM packages
- [ ] Merge this

### CODE REVIEW

**Comment by Orta21** [comment]
Im trying the ignore but it doesnt seem to be working so it ended up upgrading all the packages

**Review by RamilGaripov — APPROVED** [review]
🚢

**Comment by RamilGaripov** [comment]
> Im trying the ignore but it doesnt seem to be working so it ended up upgrading all the packages

I also havent had any luck updating a singular package.. always ends up being a bulk update :(

**Review by RamilGaripov — APPROVED** [review]
🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢

**Comment by leite08** [comment]
> Im trying the ignore but it doesnt seem to be working so it ended up upgrading all the packages

Yeah, I'm also not happy w/ Lerna and publishing packages as of now. It's not working as we expected. :/ I even used NPM publish, which is a diff beast but allows for individual package publishing.

But regardless, those should be `alpha` as this PR wasn't approved at the time, right?

**Review by Goncharo — APPROVED** [review]
:shipit:

**Pull request merged**
