### PR TITLE
RELEASE 1350 1592

### PR DESCRIPTION
**Pull request by leite08**
Ticket:
- https://github.com/metriport/metriport-internal/issues/1350
- https://github.com/metriport/metriport-internal/issues/1592

### Dependencies

- upstream: https://github.com/metriport/metriport-internal/pull/1598
- downstream: none

### Description

- https://github.com/metriport/metriport/pull/1707
- https://github.com/metriport/metriport/pull/1732
- https://github.com/metriport/metriport/pull/1715
- https://github.com/metriport/metriport/pull/1750
- https://github.com/metriport/metriport/pull/1751

### Testing

Check each PR

### Release Plan

- :warning: Points to `master`
- [x] Create DB/Schema
  - `CREATE DATABASE metriport_ihe_inbound;`
- [x] Merge upstream
- [x] Merge this
- [ ] Point local administrator instance to prod's inbound DB, login, and create user w/ pwd from 1Pwd
- [ ] Update IHE GW Config - `./scripts/push-to-cloud.sh -e production`
- [ ] Restart services
   - [ ] inbound
   - [ ] outbound

### CODE REVIEW

**Review by Goncharo — APPROVED** [review]
:shipit:

**Comment by leite08** [comment]
Converted to draft so we can ship the update to how the containers start + diff DBs for inbound/outbound together with this.

**Comment by Goncharo** [comment]
🚢

**Review by Goncharo — APPROVED** [review]
🚢

**Pull request merged**
