### PR TITLE
Add semantic versioning

### PR DESCRIPTION
**Pull request by leite08**
Ref https://github.com/metriport/metriport-internal/issues/92

### Dependencies

- Upstream: https://github.com/metriport/metriport/pull/64
- Downstream: none

### Description

Adds [semantic release](https://www.npmjs.com/package/semantic-release) to CI/CD.

Upon merge/commit into master, it should create a new tag/release/notes.

Upon merge/commit into develop, it should create a new pre-release (alpha) tag/release.

### Release Plan

- anytime

### CODE REVIEW

**Comment by leite08** [comment]
See https://github.com/metriport/metriport-internal/pull/281

**Review by Goncharo — APPROVED** [review]
🚢

**Comment by leite08** [comment]
A new commit after your approval, @Goncharo : https://github.com/metriport/metriport/pull/65/commits/c26716307f0159fa8d08e5e8854ec166e2e17467

**Review by Goncharo — APPROVED** [review]
🚢

**Pull request merged**
