### PR TITLE
Refactor Org management

### PR DESCRIPTION
**Pull request by leite08**
Ref: metriport/metriport-internal#369

### Dependencies

- Upstream: none
- Downstream: Dash TBD

### Description

Refactor Org management's types to better support Patient management.

Adjust some env vars.

Tested creating and updating an Org @ Commonwell.

### Release Plan

- [x] once approved, deploy a new version of `@metriport/api`
- [ ] merge/deploy this

### CODE REVIEW

**Review by Orta21 — APPROVED** [review]
🚢

**Review by Goncharo — APPROVED** [review]
Good to 🚢 - one nit I have is why we're using CW_ORG_NAME instead of CW_MEMBER_NAME:

CW_MEMBER_NAME is more explicit as to what it actually is, and in the code it's a bit confusing since we have:

`const metriportOrgName = getEnvVarOrFail("CW_ORG_NAME");`

but then also

`const memberName = getEnvVarOrFail("CW_ORG_NAME");`

I think all the vars should be `const memberName = getEnvVarOrFail("CW_MEMBER_NAME"); `, right?

Since this is specific for CW using `ORG_NAME` is a bit confusing imo, since there isn't really a Metriport org - rather we're a CW member.

**Comment by leite08** [comment]
> Good to 🚢 - one nit I have is why we're using CW_ORG_NAME instead of CW_MEMBER_NAME:
> 
> CW_MEMBER_NAME is more explicit as to what it actually is, and in the code it's a bit confusing since we have:
> 
> `const metriportOrgName = getEnvVarOrFail("CW_ORG_NAME");`
> 
> but then also
> 
> `const memberName = getEnvVarOrFail("CW_ORG_NAME");`
> 
> I think all the vars should be `const memberName = getEnvVarOrFail("CW_MEMBER_NAME"); `, right?
> 
> Since this is specific for CW using `ORG_NAME` is a bit confusing imo, since there isn't really a Metriport org - rather we're a CW member.

I wanted to be consistent to how we name things. [We agreed](https://metriport.slack.com/archives/C04DMKE9DME/p1677715634571389?thread_ts=1677714677.050119&cid=C04DMKE9DME) that things with "member" name are related to Org _member_ management stuff, so I wanted to be clear which properties are related to Metriport as an organization, and which ones are related to Metriport as an organization management at Commonwell.

I agree those env vars should be used the same way, and the var names should be consistent. Just pushed a new commit that I hope makes it clearer.

**Review by Goncharo — APPROVED** [review]
`metriportOrgName` should probably be `metriportMemberName` - but can 🚢  for now

**Pull request merged**
